[pytest]
testpaths = tests
pythonpath = .
addopts = -v --tb=short -p no:faulthandler
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::sklearn.exceptions.InconsistentVersionWarning
